### PR TITLE
Filter metab data based on diagnostics

### PR DESCRIPTION
**Pull request by lekoenig**
Addresses #80.

The code changes here add three targets to the DO pipeline to download and load streamMetabolizer model diagnostics that accompany the daily metabolism estimates, and to filter the metabolism data we're using based on these added diagnostics.

We decided whether to exclude a site by checking whether any site had "low" model confidence" in the diagnostics data, and by checking the overall correlation between ER and K600 (a strong correlation is likely indicative of issues with model equifinality). All of our DO sites had either "high" or "medium" model confidence so we did not exclude any sites based on this new criteria. 

However, there are still many days with negative GPP and/or positive ER (biologically implausible). 

GPP

ER

For example, ER is positive for ~30% of the metab days for 01481500. This site is the only site with "medium" confidence and we may ultimately opt to include only "high" confidence sites. In `p2_metab_filtered` two new columns are created "GPP_filtered" and "ER_filtered" where values of GPP < 0 or ER > 0 are assigned as NA:

```
> head(p2_metab_filtered) %>% as.data.frame()
      site_name resolution       date        GPP GPP.lower GPP.upper GPP.n_eff  GPP.Rhat         ER  ER.lower ER.upper ER.n_eff   ER.Rhat     K600 K600.lower
1 nwis_01473500         15 2016-03-02 0.07775512 -2.573446  2.740354      8000 0.9998001 -1.2810810 -5.677797 2.933795     8000 0.9998194 2.898010   1.763751
2 nwis_01473500         15 2016-03-02 0.07775512 -2.573446  2.740354      8000 0.9998001 -1.2810810 -5.677797 2.933795     8000 0.9998194 2.898010   1.763751
3 nwis_01473500         15 2016-03-03 0.17769523 -2.447766  2.809710      8000 1.0004541 -0.4524001 -4.731655 3.884222     8000 1.0001482 2.511884   1.546763
4 nwis_01473500         15 2016-03-03 0.17769523 -2.447766  2.809710      8000 1.0004541 -0.4524001 -4.731655 3.884222     8000 1.0001482 2.511884   1.546763
5 nwis_01473500         15 2016-03-04 0.33914259 -2.211328  2.967330      8000 1.0004003 -0.6330888 -4.785902 3.674536     8000 0.9999513 2.253151   1.375747
6 nwis_01473500         15 2016-03-04 0.33914259 -2.211328  2.967330      8000 1.0004003 -0.6330888 -4.785902 3.674536     8000 0.9999513 2.253151   1.375747
  K600.upper K600.n_eff K600.Rhat   DO.obs   DO.sat   DO.amp  DO.psat    depth temp.water day.length discharge shortwave  velocity DO.tdist80  site_id
1   4.304515   629.0753  1.003482 11.66042 11.78951 4.575137 98.91986 2.994877   7.784375      11.50  168.9321  158.5932 0.4628690   28968.69 01473500
2   4.304515   629.0753  1.003482 11.66042 11.78951 4.575137 98.91986 2.994877   7.784375      11.50  168.9321  158.5932 0.4628690   28968.69 01473500
3   3.687956   720.2368  1.003148 11.98333 12.20697 5.138691 98.16775 2.529436   6.760417      11.50  122.5589  167.9435 0.4026289   29912.72 01473500
4   3.687956   720.2368  1.003148 11.98333 12.20697 5.138691 98.16775 2.529436   6.760417      11.50  122.5589  167.9435 0.4026289   29912.72 01473500
5   3.297400   891.0441  1.002699 12.28854 12.42131 2.862222 98.93135 2.285197   5.920833      10.75  100.5926  114.1334 0.3703998   31404.54 01473500
6   3.297400   891.0441  1.002699 12.28854 12.42131 2.862222 98.93135 2.285197   5.920833      10.75  100.5926  114.1334 0.3703998   31404.54 01473500
  model_confidence site_min_confidence GPP_filtered ER_filtered
1                H                   H   0.07775512  -1.2810810
2                H                   H   0.07775512  -1.2810810
3                H                   H   0.17769523  -0.4524001
4                H                   H   0.17769523  -0.4524001
5                H                   H   0.33914259  -0.6330888
6                H                   H   0.33914259  -0.6330888
> 
```

I edited the targets in 2a_model.R to take the filtered data (`p2_metab_filtered`) rather than `p1_metab`, but I'm getting an error when building `p2a_trn_do_zarr`:
```
ValueError: cannot convert a DataFrame with a non-unique MultiIndex into xarray
```

I could use some help diagnosing this error if you have any ideas. Thanks!

### CODE REVIEW

**Comment by jsadler2** [comment]
This is great, @lekoenig. Thanks for putting this together.

I have a few questions still. Not asking you to answer them, tho, if it will take more than a few minutes:
1. How much data do we ax when we filter to just 'H' and 'M'?
2. How much would we ax if we were to do just 'H'?
3. Of each category ('L', 'M', 'H') how much data is ecologically unreasonable (neg GPP, pos ER)?

re `ValueError: cannot convert a DataFrame with a non-unique MultiIndex into xarray`
I know I've had that error recently ... and I think it might have been in this pipeline, but I can't remember for sure. I think that is meaning that there are non-unique `date` - `site_id`combinations. ... but IDK why that would be. I'll try running this tomorrow.

**Comment by lekoenig** [comment]
Good questions, @jsadler2!

> 1. How much data do we discard when we filter to just 'H' and 'M' (i.e, how much is not in 'H' and 'M')?

We actually don't discard any data when we filter to just 'H' and 'M' because all of our DRB DO sites fall under these diagnostic categories (no sites with 'L').

> 2. How much would we discard if we were to do just 'H' (i.e., how much is in just 'M')?

Across our DRB DO sites we have 19,780 metabolism obs-days. If we only use 'H' sites, we drop 2,872 obs-days (~15% of the total days). I'm inclined to do this to improve the estimates the model is using to learn relationships between inputs and GPP/ER/K600, but as a first cut I opted to be more generous with what we accept.

> 3. Of each category ('L', 'M', 'H') how much data is ecologically unreasonable (neg GPP, pos ER)?

Approximately 6% of GPP data is negative and ~11% of ER data is positive. I count ~2,980 rows where _either_ GPP is negative or ER is positive, which makes up 15% of the metabolism obs-days.

```
> p2_metab_filtered %>%
+   summarise(GPP_non_NA = sum(!is.na(GPP_filtered)),
+             GPP_NA = sum(is.na(GPP_filtered)),
+             ER_non_NA = sum(!is.na(ER_filtered)),
+             ER_NA = sum(is.na(ER_filtered))) %>%
+   mutate(percent_negGPP = GPP_NA/(GPP_non_NA + GPP_NA)*100,
+          percent_posER = ER_NA/(ER_non_NA + ER_NA)*100)
# A tibble: 1 x 6
  GPP_non_NA GPP_NA ER_non_NA ER_NA percent_negGPP percent_posER
       <int>  <int>     <int> <int>          <dbl>         <dbl>
1      18538   1242     17514  2266           6.28          11.5
>
```

And here's a breakdown of each site x model resolution, where `neg_GPP` is the percent of days where GPP is negative and `neg_ER` is the percent of days where ER is positive:

```
> p1_metab_diagnostics %>%
+   # select only those sites that are within our DRB DO dataset
+   filter(site_id %in% p2_daily_with_seg_ids$site_id) %>%
+   select(site, resolution, neg_GPP, pos_ER, model_confidence, site_min_confidence)
# A tibble: 10 x 6
   site          resolution neg_GPP pos_ER model_confidence site_min_confidence
   <chr>         <chr>        <dbl>  <dbl> <chr>            <chr>              
 1 nwis_01473500 15min       19.2   18.8   H                H                  
 2 nwis_01473500 30min       24.6   17.2   H                H                  
 3 nwis_01474500 30min        5.88  12.9   H                H                  
 4 nwis_01480617 30min        0.649  7.74  H                H                  
 5 nwis_01480617 15min        0      1.45  H                H                  
 6 nwis_01480870 15min        0.475  0.856 H                H                  
 7 nwis_01480870 30min        0.487  1.30  H                H                  
 8 nwis_01481000 15min        0.707  0.354 H                H                  
 9 nwis_01481000 30min        1.10   2.19  H                H                  
10 nwis_01481500 15min        1.18  32.1   M                M                  
>
```

Finally, _if_ we drop site 01481500 (the only 'M' site), I estimate that there are ~1890 rows with either negative GPP or positive ER, which would represent ~11% of observation days in that subset.

**Comment by jsadler2** [comment]
Thanks for looking into these, @lekoenig. Very helpful. Also apologies for not reading closely enough the original post. I'm realizing now that you answered my 1st question there. 

I lean toward taking out the 'M' site and all of the biologically implausible observations.

**Comment by lekoenig** [comment]
Sounds good, I agree with that. In [2e081ba](https://github.com/USGS-R/drb-do-ml/pull/86/commits/2e081ba75a73bc30979a4238c73588e8fe303498), I dropped the 'M' site when building `p2_metab_filtered`:

```
> dim(p2_metab_filtered)
[1] 16908    34
> p2_metab_filtered %>% group_by(site_id) %>% summarize(n_days = n())
# A tibble: 5 x 2
  site_id  n_days
  <chr>     <int>
1 01473500   2578
2 01474500    800
3 01480617   4144
4 01480870   4568
5 01481000   4818
>
```

I'd like to solve that xarray error before merging, so still need to dig in there.

**Comment by jsadler2** [comment]
I dug into the xarray thing and I see what the problem is, but I'm not sure how to fix it. 

The problem is that in the filtered metab estimates, there are multiple estimates for a single date and site: 
image

I think that has to do with the different resolutions in the diagnostics file, but I'm not sure what those different resolutions are used for or how to resolve this. I can look into it more, but wanted to check in w/ you first in case you knew a resolution off the top of your head.

**Comment by lekoenig** [comment]
OK, thanks! I'll look into that.

**Comment by lekoenig** [comment]
Thanks @jsadler2 for diagnosing that, and special thanks to xarray for complaining and calling attention to this issue! 🙌 In the function that creates `p2_metab_filtered` I was only joining the metab and diagnostics tables using "site" as a key, but because there are some sites with  _multiple_ models (representing different resolutions of the available input data), we need to include "resolution" as a join key as well.  

So the good news is that the pipeline runs after fixing that bug! 'Less good' is that we have fewer obs-days than I indicated above since rows were being duplicated for at least one site. Here's a similar data inventory after fixing the duplication issue:

```
> tar_load(p2_metab_filtered)
> dim(p2_metab_filtered)
[1] 8854   34
> p2_metab_filtered %>% group_by(site_id) %>% summarize(n_days = n())
# A tibble: 5 x 2
  site_id  n_days
  <chr>     <int>
1 01473500   1289
2 01474500    800
3 01480617   2072
4 01480870   2284
5 01481000   2409
> 
> p2_metab_filtered %>%
+   summarise(GPP_non_NA = sum(!is.na(GPP_filtered)),
+             GPP_NA = sum(is.na(GPP_filtered)),
+             ER_non_NA = sum(!is.na(ER_filtered)),
+             ER_NA = sum(is.na(ER_filtered))) %>%
+   mutate(percent_negGPP = GPP_NA/(GPP_non_NA + GPP_NA)*100,
+          percent_posER = ER_NA/(ER_non_NA + ER_NA)*100)
# A tibble: 1 x 6
  GPP_non_NA GPP_NA ER_non_NA ER_NA percent_negGPP percent_posER
       <int>  <int>     <int> <int>          <dbl>         <dbl>
1       8244    610      8175   679           6.89          7.67
> 
```

**Comment by jsadler2** [comment]
Ahh. That makes sense. Thanks for figuring that out! 

I see that you've filtered to just the 'H' now in https://github.com/USGS-R/drb-do-ml/pull/86/commits/2e081ba75a73bc30979a4238c73588e8fe303498. 

I was thinking it would make sense to filter out all of the negative GPP and positive ER. Do you agree with adding that filter?

**Comment by lekoenig** [comment]
> I was thinking it would make sense to filter out all of the negative GPP and positive ER. Do you agree with adding that filter?

Yes, I do agree with adding this filter. Rather than filtering out negative GPP or positive ER's, I added two columns `GPP_filtered` and `ER_filtered` to `p2_metab_filtered` that contain NA for the cases where these values occur. So you'd want to use those columns as input in the model. Let me know if you'd prefer to just have columns "GPP" and "ER" where we remove those days altogether.

**Comment by jsadler2** [comment]
Ohhh. Gotcha. Okay. Thanks. I didn't realize that was what those columns were. That's perfect. Thanks!

**Review by jsadler2 — APPROVED** [review]
Looks good. Thanks, @lekoenig

**Pull request merged**
